import React from "react";
import {
  Plus,
  Info,
  Save,
  IdCard,
  Download,
  Building2,
  X,
  Table,
  Upload,
  ArrowLeft,
  ArrowRight,
  Lightbulb,
  Eye,
  EyeOff,
  MapPin,
  Sparkles,
  Star,
  ChevronRight,
  ChevronLeft,
  User,
  Award,
  Store,
  UtensilsCrossed,
  Sandwich,
  Utensils,
  Check,
  UserPlus,
  Package,
  Crown,
  ReceiptText,
  Receipt,
  ShieldCheck,
  Shield,
  ImagePlus,
  BookOpen,
  Folder,
  Search,
  SearchX,
  Briefcase,
  CreditCard,
  Banknote,
  Lock,
  FileText,
  ArrowLeftRight,
  Users,
  BadgeCheck,
  ArrowUpDown,
  Palette,
  ToggleRight,
  AlertTriangle,
  Wand2,
  ListFilter,
  Filter,
  LayoutGrid,
  Rows,
  Calendar,
  Mail,
  Phone,
  BellRing,
  RefreshCw,
  Percent,
  Clock,
  BarChart2,
  BarChart3,
  TrendingUp,
  Image as ImageIcon,
  Map,
  Camera,
  CheckSquare,
  Tag,
  Cake,
  Cookie,
  Wine,
  Coffee,
  Egg,
  Pizza,
  Boxes,
  Soup,
  Droplets,
  ChefHat,
  ShoppingBag,
  ShoppingCart,
  Calculator,
  Gift,
  ShoppingBasket,
  Barcode,
  QrCode,
  Wallet,
  Landmark,
  Monitor,
  Smartphone,
  Headphones,
  Watch,
  Laptop,
  Tablet,
  Tv,
  Speaker,
  Cpu,
  Keyboard,
  Mouse,
  Printer,
  Scan,
  Power,
  BatteryCharging,
  Cable,
  Router,
  Shirt,
  Gem,
  Luggage,
  Umbrella,
  Home,
  Armchair,
  Bed,
  Lamp,
  Flower2,
  Flower,
  Trees,
  Sprout,
  Sun,
  Grid,
  DoorOpen,
  Warehouse,
  Wind,
  Bath,
  ShowerHead,
  Dumbbell,
  CircleDot,
  Circle,
  Activity,
  Flag,
  HeartPulse,
  Pill,
  ShieldPlus,
  Heart,
  Bandage,
  Smile,
  Car,
  Bike,
  Fuel,
  Wrench,
  Gauge,
  Film,
  Music,
  Theater,
  Dices,
  Gamepad2,
  Brush,
  BookCopy,
  Video,
  PartyPopper,
  DollarSign
} from "lucide-react";

export const ICON_MAP = {
  // Common / Actions
  add: Plus,
  plus: Plus,
  info: Info,
  save: Save,
  badge: IdCard,
  id_card: IdCard,
  download: Download,
  domain: Building2,
  building: Building2,
  close: X,
  x: X,
  table_rows: Table,
  table: Table,
  upload: Upload,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  lightbulb: Lightbulb,
  visibility: Eye,
  eye: Eye,
  visibility_off: EyeOff,
  eye_off: EyeOff,
  location_on: MapPin,
  map_pin: MapPin,
  pin: MapPin,
  stars: Sparkles,
  star: Star,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  person: User,
  user: User,
  man: User,
  woman: User,
  military_tech: Award,
  store: Store,
  fastfood: UtensilsCrossed,
  done: Check,
  check: Check,
  person_add: UserPlus,
  user_plus: UserPlus,
  inventory_2: Package,
  package: Package,
  workspace_premium: Crown,
  crown: Crown,
  receipt_long: ReceiptText,
  receipt: Receipt,
  rule: ShieldCheck,
  admin_panel_settings: ShieldCheck,
  shield_person: Shield,
  shield: Shield,
  image_search: ImagePlus,
  menu_book: BookOpen,
  category: LayoutGrid,
  search: Search,
  search_off: SearchX,
  restaurant: Utensils,
  work: Briefcase,
  banknote: Banknote,
  payments: Banknote,
  payment: CreditCard,
  lock: Lock,
  description: FileText,
  swap_horiz: ArrowLeftRight,
  groups: Users,
  people: Users,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  sort: ArrowUpDown,
  palette: Palette,
  toggle_on: ToggleRight,
  warning: AlertTriangle,
  auto_awesome: Sparkles,
  auto_fix_high: Wand2,
  filter_list: ListFilter,
  filter_alt: Filter,
  grid_view: LayoutGrid,
  view_agenda: Rows,
  picture_as_pdf: FileText,
  calendar_today: Calendar,
  mail: Mail,
  call: Phone,
  phone: Phone,
  notification_important: BellRing,
  sync: RefreshCw,
  percent: Percent,
  schedule: Clock,
  analytics: BarChart3,
  image: ImageIcon,
  map: Map,
  photo_camera: Camera,
  camera_alt: Camera,
  checklist: CheckSquare,
  label: Tag,
  link: Tag,
  cake: Cake,
  cookie: Cookie,
  calculate: Calculator,
  edit_note: FileText,
  assignment_return: ArrowLeftRight,
  storefront: Store,

  // Food & Drink
  bakery_dining: Cake,
  local_bar: Wine,
  icecream: Cake,
  egg_alt: Egg,
  local_pizza: Pizza,
  coffee: Coffee,
  ramen_dining: Soup,
  lunch_dining: Sandwich,
  dinner_dining: Utensils,
  breakfast_dining: Egg,
  takeout_dining: ShoppingBag,
  set_meal: Boxes,
  tapas: Utensils,
  soup_kitchen: Soup,
  water_drop: Droplets,
  liquor: Wine,
  wine_bar: Wine,
  local_cafe: Coffee,
  kitchen: ChefHat,

  // Retail & Shopping
  sell: Tag,
  local_mall: ShoppingBag,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  point_of_sale: Calculator,
  price_check: Receipt,
  card_giftcard: Gift,
  shopping_basket: ShoppingBasket,
  barcode: Barcode,
  qr_code: QrCode,
  wallet: Wallet,
  account_balance: Landmark,
  currency_exchange: ArrowLeftRight,

  // Tech / Electronics
  computer: Monitor,
  smartphone: Smartphone,
  headphones: Headphones,
  watch: Watch,
  laptop_mac: Laptop,
  tablet: Tablet,
  tv: Tv,
  speaker: Speaker,
  memory: Cpu,
  keyboard: Keyboard,
  mouse: Mouse,
  print: Printer,
  scanner: Scan,
  monitor: Monitor,
  power: Power,
  battery_charging_full: BatteryCharging,
  cable: Cable,
  router: Router,
  devices: Laptop,

  // Fashion
  checkroom: Shirt,
  dry_cleaning: Sparkles,
  laundry: Sparkles,
  styler: Sparkles,
  diamond: Gem,
  backpack: Package,
  luggage: Luggage,
  umbrella: Umbrella,

  // Home & Garden
  home: Home,
  chair: Armchair,
  bed: Bed,
  light: Lamp,
  potted_plant: Flower2,
  local_florist: Flower,
  yard: Trees,
  grass: Sprout,
  deck: Sun,
  fence: Grid,
  roofing: Home,
  window: LayoutGrid,
  door_front: DoorOpen,
  garage: Warehouse,
  vacuum: Wind,
  bathtub: Bath,
  shower: ShowerHead,

  // Sports
  fitness_center: Dumbbell,
  sports_soccer: CircleDot,
  sports_basketball: Circle,
  sports_tennis: Activity,
  sports_volleyball: Circle,
  sports_baseball: Circle,
  sports_golf: Flag,

  // Health
  spa: Sparkles,
  local_pharmacy: HeartPulse,
  medication: Pill,
  health_and_safety: ShieldPlus,
  favorite: Heart,
  healing: Bandage,
  sanitizer: Droplets,
  clean_hands: User,
  masks: Shield,
  face: Smile,

  // Auto
  directions_car: Car,
  two_wheeler: Bike,
  local_gas_station: Fuel,
  build: Wrench,
  car_repair: Wrench,
  speed: Gauge,
  oil_barrel: Package,
  electric_car: Car,

  // Media
  movie: Film,
  music_note: Music,
  theater_comedy: Theater,
  casino: Dices,
  sports_esports: Gamepad2,
  brush: Brush,
  library_books: BookCopy,
  videocam: Video,
  celebration: PartyPopper,

  // Business
  business_center: Briefcase,
  support_agent: Headphones,
  pie_chart: BarChart2,
  trending_up: TrendingUp,
  attach_money: DollarSign,
  credit_card: CreditCard
};

export function getDynamicIcon(name) {
  if (!name) return Folder;
  if (typeof name !== "string") return name;
  const normalized = name
    .toLowerCase()
    .trim()
    .replace(/[-\s]+/g, "_");
  return ICON_MAP[normalized] || ICON_MAP[name] || Folder;
}

const DynamicIcon = ({ name, icon, size = 18, className = "", ...props }) => {
  const target = icon || name;
  if (!target) return null;

  if (typeof target === "string" && /^https?:\/\//.test(target)) {
    return (
      <img
        src={target}
        alt=""
        className={`object-cover rounded inline-block ${className}`}
        style={{ width: size, height: size }}
        {...props}
      />
    );
  }

  if (
    typeof target === "function" ||
    (typeof target === "object" && target !== null && "$$typeof" in target)
  ) {
    const Component = target;
    return <Component size={size} className={className} {...props} />;
  }

  const IconComponent = getDynamicIcon(target);
  return <IconComponent size={size} className={className} {...props} />;
};

export default DynamicIcon;
